wyf7107/adk-web-puiblic

- src/app/components/canvas/canvas.component.ts
- src/app/core/models/AgentBuilder.ts
feat: Update AgentBuildRequest to accept root node data as input
> feat: Update AgentBuildRequest to accept root node data as input

- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.ts
feat: Read node data from AgentBuilderService to BuilderTab
> feat: Read node data from AgentBuilderService to BuilderTab

- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.scss
- src/app/components/canvas/canvas.component.ts
- Add tooltips
- Highlight selected tool
- Add tools header
> feat: make tools UI improvements

- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
- src/app/core/models/AgentBuilder.ts
> feat: Update yaml config

- src/app/components/canvas/canvas.component.ts
feat: Support generating YAML for sub agent
> feat: Support generating YAML for sub agent

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.ts
feat: Update agents from builder tab
> feat: Update agents from builder tab

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.scss
feat: Add mat-tab-group in the builder tab
> feat: Add mat-tab-group in the builder tab

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.scss
- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/component.module.ts
- src/app/core/services/agent-builder.service.ts
feat: Use mat-tree for sub agents list
> feat: Use mat-tree for sub agents list

- src/app/components/add-item-dialog/add-item-dialog.component.html
- src/app/components/add-item-dialog/add-item-dialog.component.scss
- src/app/components/add-item-dialog/add-item-dialog.component.spec.ts
- src/app/components/add-item-dialog/add-item-dialog.component.ts
- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
- src/app/components/chat/chat.component.html
- src/app/components/chat/chat.component.ts
- src/app/components/component.module.ts
- src/app/components/eval-tab/eval-tab.component.ts
- src/app/core/models/AgentBuilder.ts
- src/utils/yaml-utils.ts
- separate YAML utils into separate file
- upon clicking '+ Agent', a dialog will show prompting the user to enter the app name
- new dialog component
- fix agentClass to be agent_class
> feat: Create app on add agent

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.scss
feat: Add robot icon near the agent
> feat: Add robot icon near the agent

- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
- src/app/core/services/agent-builder.service.ts
feat: Add refreshSubject in the builder service.
> feat: Add refreshSubject in the builder service

- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
feat: Position the new sub agents
> feat: Position the new sub agents

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.scss
- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
- src/app/core/services/agent-builder.service.ts
> fix: Fix tools subject

- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.ts
- src/app/core/services/agent-builder.service.ts
> feat: Delete sub agent

- src/app/components/canvas/canvas.component.ts
feat: Delete the tools when deleting a sub-agent
> feat: Delete the tools when deleting a sub-agent

- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.ts
feat: Add confirmation dialog before deleting the sub-agents
> feat: Add confirmation dialog before deleting the sub-agents

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/confirmation-dialog/confirmation-dialog.component.ts
feat: Remove is root in the agent config tab
> feat: Remove is root in the agent config tab

- src/app/components/builder-tabs/builder-tabs.component.html
- src/app/components/builder-tabs/builder-tabs.component.ts
- src/app/components/canvas/canvas.component.ts
- src/app/core/services/agent-builder.service.ts
feat: Change sub agent list to local and add delete function
> feat: Change sub agent list to local and add delete function

- src/app/components/builder-tabs/builder-tabs.component.ts
fix: Fix detectChanges console error
> fix: Fix detectChanges console error

- src/app/components/add-item-dialog/add-item-dialog.component.ts
- src/app/components/canvas/canvas.component.html
- src/app/components/canvas/canvas.component.ts
- src/app/core/services/agent-builder.service.ts
- src/utils/yaml-utils.ts
- fix saving AgentToolYaml
- move sub_agent naming logic to service to avoid naming collisons
- fix unable to delete subagent from AgentTool
- update delete subagent tooltip
- fix cascading delete confirmation dialogs when deleting subagent with tools
> fix: Fix saving agent tool yaml (and various other fixes)
